import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 36,
    fontFamily: 'Helvetica',
    fontSize: 10,
    lineHeight: 1.4,
    color: '#1e293b',
  },
  header: {
    borderBottomWidth: 2,
    borderBottomColor: '#2563eb',
    paddingBottom: 10,
    marginBottom: 16,
  },
  title: {
    fontSize: 22,
    fontFamily: 'Helvetica-Bold',
    color: '#0f172a',
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 10,
    color: '#64748b',
  },
  sectionHeading: {
    fontSize: 14,
    fontFamily: 'Helvetica-Bold',
    color: '#1e3a8a',
    marginTop: 14,
    marginBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
    paddingBottom: 2,
  },
  paragraph: {
    marginBottom: 8,
    textAlign: 'justify',
  },
  bulletPoint: {
    flexDirection: 'row',
    marginBottom: 4,
    paddingLeft: 8,
  },
  bulletDot: {
    width: 12,
    fontSize: 10,
    fontFamily: 'Helvetica-Bold',
    color: '#2563eb',
  },
  bulletText: {
    flex: 1,
  },
  // Monospace styling for code blocks and ASCII text diagrams
  codeBlock: {
    fontFamily: 'Courier',
    fontSize: 8.5,
    backgroundColor: '#f8fafc',
    borderColor: '#cbd5e1',
    borderWidth: 1,
    borderRadius: 4,
    padding: 8,
    marginTop: 6,
    marginBottom: 10,
    lineHeight: 1.2,
  },
  codeText: {
    fontFamily: 'Courier',
    fontSize: 8.5,
    color: '#0f172a',
  },
  footer: {
    position: 'absolute',
    bottom: 20,
    left: 36,
    right: 36,
    textAlign: 'center',
    fontSize: 8,
    color: '#94a3b8',
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    paddingTop: 6,
  },
});

interface StudyNotesPdfDocumentProps {
  title: string;
  markdownContent: string;
}

export const StudyNotesPdfDocument: React.FC<StudyNotesPdfDocumentProps> = ({
  title,
  markdownContent,
}) => {
  // Simple parser to separate code/diagram blocks from standard paragraphs for PDF layout
  const lines = markdownContent.split('\n');
  const renderedElements: React.ReactNode[] = [];

  let inCodeBlock = false;
  let codeBuffer: string[] = [];
  let elementKey = 0;

  lines.forEach((line) => {
    if (line.trim().startsWith('```')) {
      if (inCodeBlock) {
        // End code block -> render monospace block
        renderedElements.push(
          <View key={`code-${elementKey++}`} style={styles.codeBlock}>
            <Text style={styles.codeText}>{codeBuffer.join('\n')}</Text>
          </View>
        );
        codeBuffer = [];
        inCodeBlock = false;
      } else {
        inCodeBlock = true;
      }
      return;
    }

    if (inCodeBlock) {
      codeBuffer.push(line);
      return;
    }

    if (line.startsWith('# ')) {
      renderedElements.push(
        <Text key={`h1-${elementKey++}`} style={styles.title}>
          {line.replace(/^#\s+/, '')}
        </Text>
      );
    } else if (line.startsWith('## ') || line.startsWith('### ')) {
      renderedElements.push(
        <Text key={`h2-${elementKey++}`} style={styles.sectionHeading}>
          {line.replace(/^#{2,3}\s+/, '')}
        </Text>
      );
    } else if (line.trim().startsWith('- ') || line.trim().startsWith('* ')) {
      renderedElements.push(
        <View key={`bullet-${elementKey++}`} style={styles.bulletPoint}>
          <Text style={styles.bulletDot}>•</Text>
          <Text style={styles.bulletText}>{line.trim().replace(/^[-*]\s+/, '')}</Text>
        </View>
      );
    } else if (line.trim().length > 0) {
      renderedElements.push(
        <Text key={`p-${elementKey++}`} style={styles.paragraph}>
          {line}
        </Text>
      );
    }
  });

  return (
    <Document title={title} author="ViBe Learning Platform">
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{title}</Text>
          <Text style={styles.subtitle}>ViBe Platform • Instructor-Quality Study Notes</Text>
        </View>

        {renderedElements}

        <Text
          style={styles.footer}
          render={({ pageNumber, totalPages }) =>
            `Page ${pageNumber} of ${totalPages} • Generated by ViBe Platform`
          }
          fixed
        />
      </Page>
    </Document>
  );
};
