import { IsNotEmpty, IsString } from 'class-validator';
import { JSONSchema } from 'class-validator-jsonschema';

@JSONSchema({ title: 'ChatbotQueryBody' })
export class ChatbotQueryBody {
  @JSONSchema({
    title: 'Question',
    description: 'The user question/query for the chatbot',
    example: 'What is the powerhouse of the cell?',
    type: 'string',
  })
  @IsNotEmpty()
  @IsString()
  question!: string;
}

export class ChatbotResponse {
  @JSONSchema({
    title: 'Response',
    description: 'The response text generated by the chatbot',
    type: 'string',
  })
  response!: string;
}
