FROM python:3.12

WORKDIR /app/backend/lms_engine

COPY backend/lms_engine/requirements.txt /app/backend/lms_engine/requirements.txt

RUN pip install --upgrade pip
RUN pip install -r /app/backend/lms_engine/requirements.txt

EXPOSE 8000
