FROM python:3.12

WORKDIR /app/backend-cal/lms_engine

COPY backend-cal/lms_engine/requirements.txt /app/backend-cal/lms_engine/requirements.txt

RUN pip install --upgrade pip
RUN pip install -r /app/backend-cal/lms_engine/requirements.txt

EXPOSE 8000
