# Generated by Django 4.2.16 on 2024-12-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoption',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='assessment',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, help_text='Store the correct answer. Format varies by type.', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='assessments',
            field=models.ManyToManyField(blank=True, related_name='questions', to='assessment.assessment'),
        ),
        migrations.AddField(
            model_name='question',
            name='decimal_precision',
            field=models.PositiveIntegerField(blank=True, help_text='Decimal precision required for NAT_FLOAT. Leave blank for NAT_INT.', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(default=0, help_text='Maximum marks for the question.'),
        ),
        migrations.AddField(
            model_name='question',
            name='partial_marking',
            field=models.BooleanField(default=False, help_text='Allow partial marking for MSQ (if applicable).'),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.TextField(blank=True, help_text='Comma-separated tags for question segregation.', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='tolerance_max',
            field=models.FloatField(blank=True, help_text='Maximum acceptable value for NAT (Numerical Answer Type).', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='tolerance_min',
            field=models.FloatField(blank=True, help_text='Minimum acceptable value for NAT (Numerical Answer Type).', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Time limit in seconds.', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('MSQ', 'Multiple Select Question'), ('NAT_INT', 'Numerical Answer Type (Integer)'), ('NAT_FLOAT', 'Numerical Answer Type (Float)'), ('DESC', 'Descriptive Question')], max_length=20),
        ),
        migrations.DeleteModel(
            name='AssessmentGrading',
        ),
        migrations.DeleteModel(
            name='QuestionOption',
        ),
    ]
