# Generated by Django 4.2.16 on 2024-12-02 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('assessment', '0003_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='NATSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_type', models.CharField(choices=[('int', 'Integer'), ('float', 'Float')], default='int', help_text='Type of numerical value (Integer or Float).', max_length=10)),
                ('value', models.FloatField(help_text='The correct numerical value.')),
                ('tolerance_min', models.FloatField(blank=True, help_text='Minimum acceptable value.', null=True)),
                ('tolerance_max', models.FloatField(blank=True, help_text='Maximum acceptable value.', null=True)),
                ('decimal_precision', models.PositiveIntegerField(blank=True, help_text='Decimal precision required for floats (leave blank for integers).', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='solution',
            field=models.TextField(blank=True, help_text='Store the correct solution. Format varies by type.', null=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.AddField(
            model_name='questionsolution',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='assessment.question'),
        ),
    ]
