# Generated by Django 4.2.16 on 2024-12-02 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_natsolution_questionsolution_remove_question_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='natsolution',
            name='question',
            field=models.OneToOneField(help_text='Link to the related question.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nat_solution', to='assessment.question'),
        ),
    ]
