# Generated by Django 4.2.16 on 2024-12-02 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_natsolution_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='decimal_precision',
        ),
        migrations.RemoveField(
            model_name='question',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='question',
            name='tolerance_max',
        ),
        migrations.RemoveField(
            model_name='question',
            name='tolerance_min',
        ),
    ]
