# Generated by Django 4.2.16 on 2024-12-03 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_choicesolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicesolution',
            name='marks',
        ),
        migrations.CreateModel(
            name='DescSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_answer', models.TextField(help_text='The correct or model answer for the descriptive question.')),
                ('max_word_limit', models.PositiveIntegerField(blank=True, help_text='Maximum allowed word count for the answer. Leave blank if unlimited.', null=True)),
                ('min_word_limit', models.PositiveIntegerField(blank=True, help_text='Minimum required word count for the answer. Leave blank if no minimum.', null=True)),
                ('question', models.OneToOneField(help_text='Link to the related question.', on_delete=django.db.models.deletion.CASCADE, related_name='desc_solution', to='assessment.question')),
            ],
        ),
    ]
