# Generated by Django 4.2.16 on 2024-12-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_remove_question_partial_marking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('short_video', 'Short Video'), ('long_video', 'Long Video')], max_length=50),
        ),
    ]
