# Generated by Django 4.2.16 on 2024-12-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0014_alter_assessment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(default=1, help_text='Maximum marks for the question.'),
        ),
    ]
