# Generated by Django 5.1.6 on 2025-02-12 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="courseinstructor",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="instructors",
            field=models.ManyToManyField(
                related_name="instructor_courses",
                through="course.CourseInstructor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="coursepersonnel",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course.courseinstance"
            ),
        ),
        migrations.AddField(
            model_name="coursepersonnel",
            name="personnel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="courseinstance",
            name="personnel",
            field=models.ManyToManyField(
                related_name="personnel_courses",
                through="course.CoursePersonnel",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="course.course",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="course.module",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="course.section",
            ),
        ),
        migrations.AddField(
            model_name="sectioniteminfo",
            name="section",
            field=models.ForeignKey(
                help_text="The section this item belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="section_item_info",
                to="course.section",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="course.section",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="course.source",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseinstructor",
            constraint=models.UniqueConstraint(
                fields=("course", "instructor"), name="unique_course_instructor"
            ),
        ),
        migrations.AddConstraint(
            model_name="coursepersonnel",
            constraint=models.UniqueConstraint(
                fields=("course", "personnel"), name="unique_course_personnel"
            ),
        ),
        migrations.AddConstraint(
            model_name="courseinstance",
            constraint=models.UniqueConstraint(
                fields=("course", "start_date", "end_date"),
                name="unique_course_instance",
            ),
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.UniqueConstraint(
                fields=("course", "sequence"), name="module_sequence_in_course"
            ),
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                fields=("module", "sequence"), name="section_sequence_in_module"
            ),
        ),
        migrations.AddConstraint(
            model_name="sectioniteminfo",
            constraint=models.UniqueConstraint(
                fields=("section", "sequence"), name="unique_section_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="video",
            constraint=models.UniqueConstraint(
                fields=("source", "start_time", "end_time"), name="unique_video_segment"
            ),
        ),
    ]
