# Generated by Django 4.2.16 on 2024-12-04 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('course', '0003_delete_chapter_delete_coursechapter_section_module_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('sequence', models.PositiveIntegerField(help_text='The order of this item within the section.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='course.section')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('section', 'sequence')},
            },
        ),
    ]
