# Generated by Django 4.2.17 on 2024-12-04 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_sectionitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SectionItem',
        ),
    ]
