# Generated by Django 5.1.6 on 2025-02-12 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessment", "0001_initial"),
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="course.section",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="assessment.assessment",
            ),
        ),
        migrations.AddField(
            model_name="natsolution",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="assessment.question",
            ),
        ),
        migrations.AddField(
            model_name="msqsolution",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="assessment.question"
            ),
        ),
        migrations.AddField(
            model_name="mcqsolution",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="assessment.question",
            ),
        ),
        migrations.AddField(
            model_name="descriptivesolution",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="assessment.question",
            ),
        ),
        migrations.AddField(
            model_name="questionoption",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="assessment.question",
            ),
        ),
        migrations.AddField(
            model_name="msqsolution",
            name="choice",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="assessment.questionoption",
            ),
        ),
        migrations.AddField(
            model_name="mcqsolution",
            name="choice",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mcq_solution",
                to="assessment.questionoption",
            ),
        ),
        migrations.AddConstraint(
            model_name="msqsolution",
            constraint=models.UniqueConstraint(
                fields=("question", "choice"), name="unique_msq_choice"
            ),
        ),
        migrations.AddConstraint(
            model_name="mcqsolution",
            constraint=models.UniqueConstraint(
                fields=("question", "choice"), name="unique_mcq_choice"
            ),
        ),
    ]
