# Generated by Django 4.2.16 on 2024-12-03 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('assessment', '0012_alter_assessment_type'),
        ('study_content', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='assessment.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='VideoSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_time', models.PositiveIntegerField(help_text='Start time in seconds')),
                ('end_time', models.PositiveIntegerField(help_text='End time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoSegmentAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='segment', to='assessment.assessment')),
                ('segment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='study_content.videosegment')),
            ],
        ),
        migrations.RemoveField(
            model_name='articletopic',
            name='article',
        ),
        migrations.RemoveField(
            model_name='videometadata',
            name='video',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, help_text='Content for Markdown or link to PDF/URL', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='course.chapter'),
        ),
        migrations.AlterField(
            model_name='video',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='course.chapter'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_type',
            field=models.CharField(choices=[('short', 'Short Video'), ('long', 'Long Video')], max_length=50),
        ),
        migrations.DeleteModel(
            name='ArticleAuthor',
        ),
        migrations.DeleteModel(
            name='ArticleTopic',
        ),
        migrations.DeleteModel(
            name='VideoMetadata',
        ),
        migrations.AddField(
            model_name='videosegment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='study_content.video'),
        ),
        migrations.AddField(
            model_name='videoassessment',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='study_content.video'),
        ),
    ]

# Generated by Django 4.2.16 on 2024-12-03 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('assessment', '0012_alter_assessment_type'),
        ('study_content', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='assessment.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='VideoSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_time', models.PositiveIntegerField(help_text='Start time in seconds')),
                ('end_time', models.PositiveIntegerField(help_text='End time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoSegmentAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='segment', to='assessment.assessment')),
                ('segment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='study_content.videosegment')),
            ],
        ),
        migrations.RemoveField(
            model_name='articletopic',
            name='article',
        ),
        migrations.RemoveField(
            model_name='videometadata',
            name='video',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, help_text='Content for Markdown or link to PDF/URL', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='course.chapter'),
        ),
        migrations.AlterField(
            model_name='video',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='course.chapter'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_type',
            field=models.CharField(choices=[('short', 'Short Video'), ('long', 'Long Video')], max_length=50),
        ),
        migrations.DeleteModel(
            name='ArticleAuthor',
        ),
        migrations.DeleteModel(
            name='ArticleTopic',
        ),
        migrations.DeleteModel(
            name='VideoMetadata',
        ),
        migrations.AddField(
            model_name='videosegment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='study_content.video'),
        ),
        migrations.AddField(
            model_name='videoassessment',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='study_content.video'),
        ),
    ]
