# Generated by Django 4.2.16 on 2024-12-04 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_delete_chapter_delete_coursechapter_section_module_and_more'),
        ('study_content', '0008_remove_video_chapter_video_module_delete_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='module',
        ),
        migrations.AddField(
            model_name='video',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='course.section'),
        ),
    ]
