# Generated by Django 4.2.16 on 2024-12-04 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_content', '0010_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videosegment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='videosegment',
            name='sequence',
        ),
    ]
