# Generated by Django 4.2.16 on 2024-12-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_content', '0011_remove_videosegment_end_time_and_more'),
    ]

    operations = [

    ]
