# Generated by Django 4.2.16 on 2024-12-04 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_content', '0012_remove_videosegment_unique_sequence_per_video_and_more'),
    ]

    operations = [

    ]
