# Generated by Django 4.2.16 on 2024-12-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_content', '0013_remove_videosegment_unique_sequence_per_video'),
    ]

    operations = [

    ]
