# Generated by Django 4.2.16 on 2024-12-04 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_content', '0014_videosegment_sequence_and_more'),
    ]

    operations = [

    ]
