# Generated by Django 4.2.16 on 2024-12-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_content', '0015_remove_videosegment_unique_sequence_per_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosegment',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
