# Generated by Django 4.2.16 on 2024-12-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_content', '0016_videosegment_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(default='jbiudh', max_length=255),
        ),
    ]
