# Generated by Django 4.2.16 on 2024-12-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_content', '0017_video_youtube_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(max_length=255),
        ),
    ]
