# Generated by Django 4.2.17 on 2024-12-04 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_delete_sectionitem'),
        ('study_content', '0018_alter_video_youtube_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['sequence']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['sequence']},
        ),
        migrations.AddField(
            model_name='article',
            name='sequence',
            field=models.PositiveIntegerField(default=1, help_text='The order of this item within the section.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='sequence',
            field=models.PositiveIntegerField(default=1, help_text='The order of this item within the section.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, help_text='Content for Markdown', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='section',
            field=models.ForeignKey(help_text='The section this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='course.section'),
        ),
        migrations.AlterField(
            model_name='video',
            name='section',
            field=models.ForeignKey(default=1, help_text='The section this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='course.section'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('section', 'sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('section', 'sequence')},
        ),
        migrations.RemoveField(
            model_name='article',
            name='content_type',
        ),
    ]
