# Generated by Django 4.2.17 on 2024-12-05 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_image'),
        ('user', '0002_usercourses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCourses',
            new_name='UserCourse',
        ),
    ]
