# Generated by Django 4.2.16 on 2024-11-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('Activity', 'Activity'), ('Error', 'Error'), ('Audit', 'Audit')], max_length=50)),
                ('severity', models.CharField(blank=True, choices=[('Info', 'Info'), ('Warning', 'Warning'), ('Critical', 'Critical')], max_length=50, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
