// sidebarsNew.js
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebarsNew = {
  newSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',   // scans the `newdocs/` folder by default
    },
  ],
};

export default sidebarsNew;
