ASSESSMENT_TITLE_MAX_LEN = 255
ASSESSMENT_QUESTION_VISIBILITY_LIMIT_MIN_VAL = 1
ASSESSMENT_QUESTION_VISIBILITY_LIMIT_MAX_VAL = 10
ASSESSMENT_TIME_LIMIT_MIN_VAL = 1
ASSESSMENT_TIME_LIMIT_MAX_VAL = 3600

QUESTION_OPTION_TEXT_MAX_LEN = 255

QUESTION_TEXT_MAX_LEN = 1000
QUESTION_HINT_MAX_LEN = 255
QUESTION_MARKS_MIN_VAL = 1
QUESTION_MARKS_MAX_VAL = 1000

SOLUTION_EXPLANATION_MAX_LEN = 1000

MODEL_DESCRIPTIVE_SOLUTION_MAX_LEN = 1000
