name: Lint and Format Check on Pull Request

on:
  pull_request:
    branches:
      - combined-updates
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-backend:
    name: Lint Backend
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_dispatch' ||
      contains(toJson(github.event.pull_request.changed_files), 'backend/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install
        working-directory: backend

      - name: Lint Backend Code
        run: pnpm run lint
        working-directory: backend

  lint-frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_dispatch' ||
      contains(toJson(github.event.pull_request.changed_files), 'frontend/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install
        working-directory: frontend

      - name: Lint Frontend Code
        run: pnpm run lint
        working-directory: frontend